**Оцінювання даної роботи буде ураховувати якість Вашого коду та текстових відповідей. При наявності ЛИШЕ коду , робота оцінюватися НЕ БУДЕ.**  

**Оформлення текстових відповідей повинно проводитися в текстових комірках ноутбука з використанням синтаксису [LaTeX](https://en.wikibooks.org/wiki/LaTeX/Basics) для оформлення тексту та формул.**

**Роботи ідентифіковані як ІДЕНТИЧНІ одразу отримують 0 балів.**

**При реалізації завдань потрібно використовувати методи з бібліотеки numpy та pandas.**

**Рішення з циклами будуть оцінені в 0 балів.**

# I. NumPy.

0. Імпортувати numpy загальноприйнятим способом.

In [ ]:
import numpy as np

1. Визначити список з оцінками студента(ки) за семестр. Використовуючи його, створити одновимірний масив numpy.

In [ ]:
points = [2, 2, 3, 4, 5, 4, 4, 3, 4, 5]
pointsArray = np.array(points)
print(pointsArray)


[2 2 3 4 5 4 4 3 4 5]


2. Визначити список зі списками, де кожен рядок списку формально означає магазин, а кожна колонка - певний продукт (батон, яйця першої категорії, молоко та ковбаса), а елементами на пересічі є ціни на ці продукти відповідно. Використовуючи цей список, створити матрицю (двовимірний масив) numpy.

In [ ]:
price = [["          "," Bread   ", "  Eggs   ", "   Milk  ", " Sausages "],
         ["firstShop ","  50$    ", "   60$    ", "   55$   ", "   60$    "],
         ["secondShop","  10$    ", "   15$    ", "   13$   ", "   12$    "],
         ["thirdShop ","  30$    ", "   40$    ", "   35$   ", "   20$    "],
         ["fourthShop","  10$    ", "   15$    ", "   13$   ", "   12$    "],

        ]
priceMatrix = np.array(price)
print(priceMatrix)

[['          ' ' Bread   ' '  Eggs   ' '   Milk  ' ' Sausages ']
 ['firstShop ' '  50$    ' '   60$    ' '   55$   ' '   60$    ']
 ['secondShop' '  10$    ' '   15$    ' '   13$   ' '   12$    ']
 ['thirdShop ' '  30$    ' '   40$    ' '   35$   ' '   20$    ']
 ['fourthShop' '  10$    ' '   15$    ' '   13$   ' '   12$    ']]


3. Отримайте тип даних значень з масивів завдань 2 та 3. Виведіть їх на екран.

In [ ]:
print("pointsArray: ", pointsArray.dtype, "\n","priceMatrix: ", priceMatrix.dtype)

pointsArray:  int64 
 priceMatrix:  <U10


4. Отримайте форми (кортеж з кількістю рядків та колонок) масивів завдань 2 та 3. Виведіть їх на екран.

In [ ]:
shapeArray = pointsArray.shape
shapeMatrix = priceMatrix.shape
print("pointsArray: ",shapeArray, "\n","priceMatrix: ", shapeMatrix)

pointsArray:  (10,) 
 priceMatrix:  (5, 5)


5. Створіть одновимірний масив за допомогою спеціальної функції numpy, який би відображав динаміку стабільно зростаючого (з рівними проміжками) прибутку з продажів  за тиждень, де у перший день не було продажів, а в останній день тижня вдалося заробити 1000 грн 50 коп.

In [ ]:
growth = np.linspace(0, 1000.50, 7)
print(growth)

[   0.    166.75  333.5   500.25  667.    833.75 1000.5 ]


6. Створіть два масиви. Використовуючи їх, продемонструйте відмінність вертикального та горизонтального обʼєднання масивів.

In [ ]:
firstArray = [2, 6, 5]
secondArray = [8, 1, 4]

verticalArray = np.vstack((firstArray, secondArray))
horizontalArray = np.hstack((firstArray, secondArray))

print("Vertical array: ","\n", verticalArray)
print("Horizontal array: ","\n", horizontalArray)

Vertical array:  
 [[2 6 5]
 [8 1 4]]
Horizontal array:  
 [2 6 5 8 1 4]


7. Визначити функцію, яка приймає на вході масив і транспонує його. Скористайтесь методом reshape. І не забудьте почати з docstrings.

In [ ]:
reshapedArray = pointsArray.reshape(2, 5)
print(reshapedArray)

[[2 2 3 4 5]
 [4 4 3 4 5]]


8. Створіть два масиви. Використовучи ці масиви, продемонструйте 1) операцію по-елементного додавання, 2) операцію по-елементного віднімання, 3) множення масиву на число, 4) операцію по-елементного множення, і 5) матричного множення.

In [ ]:
arrayFirst = np.array([4, 5, 3, 1])
arraySecond = np.array([8, 9, 0, 2])

arraySum = arrayFirst + arraySecond
print("1) ", arraySum)

arraySubtraction = arrayFirst - arraySecond
print("2) ", arraySubtraction)

arrayScaledFirst = arrayFirst * 2
arrayScaledSecond = arraySecond * 3
print("3) ", arrayScaledFirst, arrayScaledSecond)

arrayMultiplication = arrayFirst * arraySecond
print("4) ", arrayMultiplication)

firstMatrix = arrayFirst.reshape(2, 2)
secondMatrix = arraySecond.reshape(2, 2)
matrixMultiplication = np.dot(firstMatrix, secondMatrix)
print("5) \n", matrixMultiplication)

1)  [12 14  3  3]
2)  [-4 -4  3 -1]
3)  [ 8 10  6  2] [24 27  0  6]
4)  [32 45  0  2]
5) 
 [[32 46]
 [24 29]]


9. Створіть двовимірний масив (матрицю) та розрахуйте: 1) мінімальне число, 2) максимальне число, 3) суму чисел, 4) мінімальні числа для кожного рядка, 5) максимальні числа для кожного стовпчика.

In [ ]:
matrix = np.array([[1, 0, 5], [2, 8, 6]])

minNum = np.min(matrix)
print("1)", minNum)

maxNum = np.max(matrix)
print("2)", maxNum)

sumNum = np.sum(matrix)
print("3)", sumNum)

minNumRow = np.min(matrix, axis = 1)
print("4)", minNumRow)

maxNumColumn = np.max(matrix, axis = 0)
print("5)", maxNumColumn)


1) 0
2) 8
3) 22
4) [0 2]
5) [2 8 6]


10. Створіть матрицю , де деякі елементи повторюються. Знайдіть унікальні значення елементів цієї матриці та їхні частоти.

In [ ]:
matrixWithRepeat = [[1, 2, 2], [4, 5, 6], [5, 4, 8], [8, 3, 2]]
uniqueNum, counter = np.unique(matrixWithRepeat, return_counts = True)

for value, count in zip(uniqueNum, counter):
  print("Numeric ", value, "counter ", count)

Numeric  1 counter  1
Numeric  2 counter  3
Numeric  3 counter  1
Numeric  4 counter  2
Numeric  5 counter  2
Numeric  6 counter  1
Numeric  8 counter  2


# II. Importing. Creating DF

0. Імпортувати бібліотеку pandas

In [ ]:
import pandas as pd

11. Створити тестовий датафрейм зі списку, що містить записи пацієнтів про їхні прізвища, імена, дату народження, масу тіла та наявність медичного страхування. Одне зі значень зробить пустим. Ознайомтесь з типом кожної колонки.

In [ ]:
hospitalData = [["Fairfield", "Dwight", 1990, 70, True],
                ["Thomas", "Meg", 1999, 50, False],
                ["Park", "Jake", 1996, 74, True],
                ["Min", None, 2000, 53, True]]

df = pd.DataFrame(hospitalData, columns=["lastName", "firstName", "dateOfBirth", "weight", "healthInsurance"])

print(df.dtypes)

lastName           object
firstName          object
dateOfBirth         int64
weight              int64
healthInsurance      bool
dtype: object


# III. Reading from file

12. Завантажити файл missile_attacks_daily.csv з [Kaggle](https://www.kaggle.com/datasets/piterfm/massive-missile-attacks-on-ukraine?select=missile_attacks_daily.csv). Ознайомитись з описом датасету. Додати файл до папки поточної сесії colab notebook на панелі ліворуч або на гугл диск (локально до проєкту, якщо працюєте у пайчармі). Зчитати датафрейм з файлу та вивести датафрейм на екран. Зверніть увагу на те, щоб всі колонки відповідали наведеним у описі типам даних.

In [ ]:
from google.colab import files
uploaded = files.upload()

df = pd.read_csv('missile_attacks_daily.csv')
print(df)

Saving missile_attacks_daily.csv to missile_attacks_daily (6).csv
            time_start          time_end               model  \
0     2025-02-01 21:00  2025-02-02 09:00      Shahed-136/131   
1     2025-01-31 19:00  2025-02-01 09:00           X-59/X-69   
2     2025-01-31 19:00  2025-02-01 09:00               X-31P   
3     2025-01-31 19:00  2025-02-01 09:00           X-22/X-32   
4     2025-01-31 19:00  2025-02-01 09:00         X-101/X-555   
...                ...               ...                 ...   
2069  2022-10-01 12:00  2022-10-01 12:00            Orlan-10   
2070        2022-09-30        2022-09-30            Orlan-10   
2071  2022-09-29 23:00  2022-09-29 23:59      Shahed-136/131   
2072        2022-09-28        2022-09-28                X-59   
2073        2022-09-28        2022-09-28  Reconnaissance UAV   

                                           launch_place  \
0     Primorsko-Akhtarsk and Kursk oblast and Oryol ...   
1                                       Voronez

# IV. Data understanding

13. Виведіть на екран перші 10 рядків зчитаного датафрейму.

In [ ]:
print(df.head(10))

         time_start          time_end             model  \
0  2025-02-01 21:00  2025-02-02 09:00    Shahed-136/131   
1  2025-01-31 19:00  2025-02-01 09:00         X-59/X-69   
2  2025-01-31 19:00  2025-02-01 09:00             X-31P   
3  2025-01-31 19:00  2025-02-01 09:00         X-22/X-32   
4  2025-01-31 19:00  2025-02-01 09:00       X-101/X-555   
5  2025-01-31 19:00  2025-02-01 09:00    Shahed-136/131   
6  2025-01-31 19:00  2025-02-01 09:00  Iskander-M/KN-23   
7  2025-01-31 19:00  2025-02-01 09:00        Iskander-K   
8  2025-01-31 19:00  2025-01-31 21:00          Orlan-10   
9  2025-01-31 19:00  2025-01-31 20:05        Iskander-M   

                                        launch_place   target  carrier  \
0  Primorsko-Akhtarsk and Kursk oblast and Oryol ...  Ukraine      NaN   
1                                    Voronezh oblast  Ukraine      NaN   
2                                          Black Sea  Ukraine      NaN   
3                                                NaN  

14. Отримайте інформацію про форму датафрейму.

In [ ]:
print(df.shape)

(2074, 17)


15. Отримайте дані про кожну колонку з її назвою, типом даних та кількістю непустих значень.

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2074 entries, 0 to 2073
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   time_start            2074 non-null   object 
 1   time_end              2074 non-null   object 
 2   model                 2074 non-null   object 
 3   launch_place          1049 non-null   object 
 4   target                2046 non-null   object 
 5   carrier               227 non-null    object 
 6   launched              2071 non-null   float64
 7   destroyed             2074 non-null   object 
 8   not_reach_goal        171 non-null    float64
 9   cross_border_belarus  33 non-null     float64
 10  back_russia           35 non-null     float64
 11  still_attacking       31 non-null     float64
 12  affected region       7 non-null      object 
 13  destroyed_details     308 non-null    object 
 14  launched_details      4 non-null      object 
 15  launch_place_details 

16. Отримайте статистику для колонок числового типу.

In [ ]:
print(df.describe())

          launched  not_reach_goal  cross_border_belarus  back_russia  \
count  2071.000000      171.000000             33.000000    35.000000   
mean     11.100435       21.701754              2.303030     2.000000   
std      22.032465       19.785882              2.023068     1.137593   
min       1.000000        1.000000              1.000000     1.000000   
25%       1.000000        4.500000              1.000000     1.000000   
50%       2.000000       17.000000              2.000000     2.000000   
75%       9.000000       31.000000              2.000000     3.000000   
max     193.000000      105.000000             10.000000     5.000000   

       still_attacking  
count        31.000000  
mean          2.709677  
std           2.818907  
min           1.000000  
25%           1.000000  
50%           1.000000  
75%           3.500000  
max          10.000000  


17. Отримати кількість унікальних значень у кожній колонці. Вивести на екран значення та кількість цих значень у колонці, яка має найменше унікальних значень.

In [ ]:
minUnique = df.nunique().idxmin()
minCount = df[minUnique].value_counts()

print(minCount)

launched_details
{'X-101/X-555': 50, 'Kalibr': 12}                     1
{'X-101/X-555': 55, 'Kalibr': 24, 'Iskander-K': 7}    1
{'X-101/X-555': 57, 'Kalibr': 28}                     1
{'X-101/X-555': 77, 'Kalibr': 28, 'X-59/X-69': 10}    1
Name: count, dtype: int64


18. На основі отриманої інформації про датасет вище, опишіть по пунктах, що б ви виправили або на що б звернули увагу на кроці очищення даних і чому?

**місце для текстової відповіді**

1.   Пункт списку
2.   Пункт списку

...


1) Очищення від дублікатів
2) Виправлення аномалій

# V. Data Cleaning

19. Перетворити колонку launched у цілочислену (Int64). Перевірити, чи все пройшло, як очікувалось.

In [ ]:
df["launched"] = df["launched"].astype("Int64")
print(df["launched"].dtypes)

Int64


20. Видалити колонки, де кількість непустих значень становить менше 30% від загальної кількості записів.

In [ ]:
empty = 0.3 * len(df)
df = df.dropna(axis=1, thresh=empty)
print(df)

            time_start          time_end               model  \
0     2025-02-01 21:00  2025-02-02 09:00      Shahed-136/131   
1     2025-01-31 19:00  2025-02-01 09:00           X-59/X-69   
2     2025-01-31 19:00  2025-02-01 09:00               X-31P   
3     2025-01-31 19:00  2025-02-01 09:00           X-22/X-32   
4     2025-01-31 19:00  2025-02-01 09:00         X-101/X-555   
...                ...               ...                 ...   
2069  2022-10-01 12:00  2022-10-01 12:00            Orlan-10   
2070        2022-09-30        2022-09-30            Orlan-10   
2071  2022-09-29 23:00  2022-09-29 23:59      Shahed-136/131   
2072        2022-09-28        2022-09-28                X-59   
2073        2022-09-28        2022-09-28  Reconnaissance UAV   

                                           launch_place  \
0     Primorsko-Akhtarsk and Kursk oblast and Oryol ...   
1                                       Voronezh oblast   
2                                             Black Se

21. Очистити датафрейм від дублікатів (дублюючихся рядків) та записів, де атака продовжувалась відʼємну або нульову кількість часу (що фізично неможливо). Не забудьте оновити індекс. Скільки рядків було видалено? Як ви це перевірили у коді?

In [ ]:
df["time_start"] = pd.to_datetime(df["time_start"], errors='coerce')
df["time_end"] = pd.to_datetime(df["time_end"], errors='coerce')

df = df.drop_duplicates()
df = df[df["time_end"] > df["time_start"]]
df = df.reset_index(drop=True)

print(df)

             time_start            time_end           model  \
0   2025-02-01 21:00:00 2025-02-02 09:00:00  Shahed-136/131   
1   2025-01-31 19:00:00 2025-02-01 09:00:00       X-59/X-69   
2   2025-01-31 19:00:00 2025-02-01 09:00:00           X-31P   
3   2025-01-31 19:00:00 2025-02-01 09:00:00       X-22/X-32   
4   2025-01-31 19:00:00 2025-02-01 09:00:00     X-101/X-555   
..                  ...                 ...             ...   
456 2022-10-06 15:00:00 2022-10-06 20:00:00       Mohajer-6   
457 2022-10-06 09:00:00 2022-10-06 11:30:00  Shahed-136/131   
458 2022-10-06 09:00:00 2022-10-06 11:30:00       Mohajer-6   
459 2022-10-02 00:00:00 2022-10-02 02:00:00  Shahed-136/131   
460 2022-09-29 23:00:00 2022-09-29 23:59:00  Shahed-136/131   

                                          launch_place  \
0    Primorsko-Akhtarsk and Kursk oblast and Oryol ...   
1                                      Voronezh oblast   
2                                            Black Sea   
3          

**місце для текстової відповіді**

Після очищення датафрейму від дублікатів та від від'ємного часу, було видалено 1613 рядків. У коді це було перевірено за допомогою функції drop_dublicate (на перевірку дублікатів) та за допомогою функції pd.to_datetime, яка добавляє за замовчуванням до всіх дат нулі в часі, де їх не було, щоб не порушувати структуру.


22. Виведіть на екран всі рядки, де є хоч одне пропущене значення.

In [ ]:
AtLeastOneNull = df[df.isnull().any(axis=1)]
result = AtLeastOneNull.reset_index(drop=True)
print(result)

             time_start            time_end           model launch_place  \
0   2025-01-31 19:00:00 2025-02-01 09:00:00       X-22/X-32          NaN   
1   2025-01-31 19:00:00 2025-02-01 09:00:00     X-101/X-555          NaN   
2   2025-01-03 12:00:00 2025-01-03 20:00:00       X-59/X-69          NaN   
3   2025-01-03 12:00:00 2025-01-03 20:00:00      Iskander-M          NaN   
4   2025-01-03 12:00:00 2025-01-03 20:00:00           C-300          NaN   
..                  ...                 ...             ...          ...   
117 2022-10-06 15:00:00 2022-10-06 20:00:00       Mohajer-6          NaN   
118 2022-10-06 09:00:00 2022-10-06 11:30:00  Shahed-136/131          NaN   
119 2022-10-06 09:00:00 2022-10-06 11:30:00       Mohajer-6          NaN   
120 2022-10-02 00:00:00 2022-10-02 02:00:00  Shahed-136/131          NaN   
121 2022-09-29 23:00:00 2022-09-29 23:59:00  Shahed-136/131          NaN   

                               target  launched destroyed  \
0                         